language: node_js
node_js:
- 10
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - node_modules
install:
- npm ci
script:
- npm run test:unit
- "$(npm bin)/cypress run --record"
after_script:
- cat ./coverage/lcov.info | coveralls
after_success:
- npm run build
before_deploy: ./before_deploy.sh
deploy:
  provider: heroku
  api_key:
    secure: M1M+el2i48cNQI2tCrRbI35W6kOvfWYsWnMdaZa8ZN1ZRwT4rQVGfBBiaQ4O6/8moFB+a8YP4CxeI1S0O9lt41CAK/GMQ83SG2dYaD0/KQ2e4lLbSHpLwQHP9aafsWQm6HvKD3sNZHyuYP+CVN7pblXAnES9zD3wHjuur0rCNrm4Ioh88s8wMzETsgyWV1nOrRjHQIFaAc0Q1JL5u7nvQqVELFNzlm6/B9UWzk52nHyuvJesJuS4B5NnmMat2o1F4pwWueOKLKLt9OVekKCm4L5J9IsSBrb9LYHhPdFJAJTZ0Dmm/E8DuyVveEQ/rNF5p03UMMdu1cpuJh5xVUrvfHHzvu5AhgPNEGNOHXFPQukX9h5TH2tSmyTkOR5gxaAskPGjpxOtLnziyIzJ2f73a33THu2NCQgON7YfLbfZMgn3OsYZp46if4aWvhv11O3B0hYkp3OKbq4RAmIqEgI6RyXSpBp4HUoeGWNaI2ZpywCwdIv0xHrKCZ/XijPq8nY8ZTgjpPds9iwUi5JO59oYePJexGfpqI8BHU92NXKsTBycTEnBTHXop5x+amxqzSTQe1nWWfAgv+jtC8twun7QdxE04CY9Km2FIQvovd2G0SXcixEPvTLdA2uD3G1Qx+Zffj/WoxshmgIk77YA2oCKEQwK0kwPe6eOT/EeOh956ao=
  app:
    staging: reeach
after_deploy: ./after_deploy.sh