language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm ci
script:
  - npm run test:unit
  - npm run test-e2e:open
  - npm run test-e2e
after_script:
  - cat ./coverage/lcov.info | coveralls